steps:
  # Step 1: Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ziplay-new'
      - './Frontend'  # Specify the frontend folder as context

  # Step 2: Push Docker Image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ziplay-new'

  # Step 3: Fetch secrets from Secret Manager and Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "Fetching secrets from Secret Manager..."

        # Fetch secrets and set them as environment variables
        export VITE_FIREBASE_API_KEY=$(gcloud secrets versions access latest --secret="VITE_FIREBASE_API_KEY")
        export VITE_AUTH_DOMAIN=$(gcloud secrets versions access latest --secret="VITE_AUTH_DOMAIN")
        export VITE_PROJECT_ID=$(gcloud secrets versions access latest --secret="VITE_PROJECT_ID")
        export VITE_STORAGE_BUCKET=$(gcloud secrets versions access latest --secret="VITE_STORAGE_BUCKET")
        export VITE_MESSAGING_SENDER_ID=$(gcloud secrets versions access latest --secret="VITE_MESSAGING_SENDER_ID")
        export VITE_APP_ID=$(gcloud secrets versions access latest --secret="VITE_APP_ID")
        export VITE_MEASUREMENT_ID=$(gcloud secrets versions access latest --secret="VITE_MEASUREMENT_ID")

        # Deploy the app to Cloud Run with the secrets as environment variables
        gcloud run deploy ziplay-new \
          --image=gcr.io/$PROJECT_ID/ziplay-new \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated \
          --update-env-vars \
            VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY,\
            VITE_AUTH_DOMAIN=$VITE_AUTH_DOMAIN,\
            VITE_PROJECT_ID=$VITE_PROJECT_ID,\
            VITE_STORAGE_BUCKET=$VITE_STORAGE_BUCKET,\
            VITE_MESSAGING_SENDER_ID=$VITE_MESSAGING_SENDER_ID,\
            VITE_APP_ID=$VITE_APP_ID,\
            VITE_MEASUREMENT_ID=$VITE_MEASUREMENT_ID

# Optional: You can specify images here to be built
images:
  - 'gcr.io/$PROJECT_ID/ziplay-new'
