- name: Fetch Secrets and Deploy to Cloud Run
  run: |
    echo "Fetching secrets from Secret Manager..."

    # Fetch and export secrets as environment variables
    export VITE_APP_ID=$(gcloud secrets versions access latest --secret="VITE_APP_ID")
    export VITE_AUTH_DOMAIN=$(gcloud secrets versions access latest --secret="VITE_AUTH_DOMAIN")
    export VITE_FIREBASE_API_KEY=$(gcloud secrets versions access latest --secret="VITE_FIREBASE_API_KEY")
    export VITE_MEASUREMENT_ID=$(gcloud secrets versions access latest --secret="VITE_MEASUREMENT_ID")
    export VITE_MESSAGING_SENDER_ID=$(gcloud secrets versions access latest --secret="VITE_MESSAGING_SENDER_ID")
    export VITE_PROJECT_ID=$(gcloud secrets versions access latest --secret="VITE_PROJECT_ID")
    export VITE_STORAGE_BUCKET=$(gcloud secrets versions access latest --secret="VITE_STORAGE_BUCKET")

    # Logging for debugging
    echo "VITE_FIREBASE_API_KEY: $VITE_FIREBASE_API_KEY"  # Log to check if the key is fetched correctly (be careful not to log sensitive data)

    # Deploy to Cloud Run with environment variables
    gcloud run deploy ziplay-new \
      --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/ziplay-new \
      --platform=managed \
      --region=us-central1 \
      --allow-unauthenticated \
      --update-env-vars \
        VITE_APP_ID="$VITE_APP_ID",\
        VITE_AUTH_DOMAIN="$VITE_AUTH_DOMAIN",\
        VITE_FIREBASE_API_KEY="$VITE_FIREBASE_API_KEY",\
        VITE_MEASUREMENT_ID="$VITE_MEASUREMENT_ID",\
        VITE_MESSAGING_SENDER_ID="$VITE_MESSAGING_SENDER_ID",\
        VITE_PROJECT_ID="$VITE_PROJECT_ID",\
        VITE_STORAGE_BUCKET="$VITE_STORAGE_BUCKET"
